### ISSUE TITLE
On second launch I start getting a Black screen and Failure to write entry:[]

### ISSUE THREAD

**Issue by Changhochien** [rvion/CushyStudio#131]
On the second launch I start, I'm getting the error below and cannot figure out how to solve the issue.

Starting Vite with Electron's Node...

Server running on http://localhost:8688
waiting for cushy to start
[VITE] vite started
|2024-01-24T14:15:42.952Z|
failure to write entry: []
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.041Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.042Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.044Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.044Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.045Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.046Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.049Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'
|2024-01-24T14:15:43.049Z|
failure to write entry: [null]
...on error: Error: ENOENT: no such file or directory, open 'D:\CushyStudio\logs\2024-01-24.debug.log'

![image](https://github.com/rvion/CushyStudio/assets/67751273/fe75136f-b946-4d47-b7e2-61b3f3cfacfb)

**Comment by rvion** [comment]
thanks for the feedback, I will look into this in ~4/5 hours when I'm home.

Does cushy start and work properly in the meantime ?

things you can try in the meantime to get rid of the logs error: creating a `logs` folder at the root of your cushy install

**Comment by GitWilburn** [comment]
@rvion Not sure if this will help, but I am seeing this error in the console in addition to the
"failure to write entry: []" error. But I am only seeing it when running with _windows-start.bat
![image](https://github.com/rvion/CushyStudio/assets/153457815/1016bd96-9276-4561-a26c-8549072f1277)

Also, @Changhochien, I was able to run okay with _windows-start-dev.bat. You could try running the -dev file in your environment as a temporary workaround until @rvion has a chance to look at it.

**Comment by rvion** [comment]
@GitWilburn are you back on master branch ?

**Comment by GitWilburn** [comment]
> @GitWilburn are you back on master branch ?

Yes, I am on master ATM.

**Comment by rvion** [comment]
@GitWilburn the error you see is probably a choices widget having its children defined without lambda; is this a default app or a custom one ?

**Comment by GitWilburn** [comment]
@rvion just the built-in SDUI. Sounds like maybe unrelated to the original issue.

**Comment by Changhochien** [comment]
> regaring the `quota_database.cc(950) Could not open the quota database, resetting.` => maybe a permission error ? Cushy should not require any privilege; install script should be run as normal user, not superadmin

I've tried on another computer and got the same problem.
I'll keep trying.
Thank you for the reply.

**Comment by Changhochien** [comment]
> @rvion Not sure if this will help, but I am seeing this error in the console in addition to the "failure to write entry: []" error. But I am only seeing it when running with _windows-start.bat ![image](https://private-user-images.githubusercontent.com/153457815/299464753-1016bd96-9276-4561-a26c-8549072f1277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDgxNDcsIm5iZiI6MTcwNjE0Nzg0NywicGF0aCI6Ii8xNTM0NTc4MTUvMjk5NDY0NzUzLTEwMTZiZDk2LTkyNzYtNDU2MS1hMjZjLTg1NDkwNzJmMTI3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwMTU3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjdlZTZhYWQ0ODRjNDg2MjM1MGU5MDJkOGRhODExNzhhNmQ3MzllYWQ3ZjQzYjRjNmE1M2FkNmVjOTVkOTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tcq-5QTdH8u74L1n1FI92xLdBzdusv5vP8xYly19JEc)
> 
> Also, @Changhochien, I was able to run okay with _windows-start-dev.bat. You could try running the -dev file in your environment as a temporary workaround until @rvion has a chance to look at it.

I've tried to run on dev mode, but I still get a black screen with the same problem.
I've up dated the screen shot on top.

**Comment by Changhochien** [comment]
New update
This problem seems to occur after first connection with comfyUI.
Then it will show a complete black screen and the errors shown in the previous dialogs.

**Comment by rvion** [comment]
fixed it in my dev branch

**Comment by rvion** [comment]
will merge in a few minutes

**Comment by rvion** [comment]
@Changhochien can you check if it works now ? 
thanks again for the help troubleshooting that :)

**Comment by R-ES-H** [comment]
I have the same black screen on second launch but the cmd.exe is stuck here :
![image](https://github.com/rvion/CushyStudio/assets/32777904/1372fbbd-ae0d-4473-847a-cf981137e289)
I have this error too, I don't know if this is related
![image](https://github.com/rvion/CushyStudio/assets/32777904/43327ece-99c9-471c-9abb-e3665f72dea9)

**Comment by rvion** [comment]
oh, you don't have git; update is using git; 
this is unfortunate :/ (in case you're opened to installing it: https://git-scm.com/ )
I plan to remove the need to have git installed; maybe I need to prioritize this.

**Comment by Changhochien** [comment]
I'll try the new update thanks!
Will update my situation soon.

**Comment by cjbarnes22** [comment]
I have git installed (at least I believe so on the host, and am not using a venv?) but am getting the [VITE] vite started on second launch. Worked on the first launch great. Now only works with a rull reinstall and keeping it online full time.

**Comment by rvion** [comment]
Can you paste the errors you have ? Both in the terminal / console, and app devtools (if app launch, using the menu entry)

**Comment by cjbarnes22** [comment]
Sorry busy week. I have had some other issues since so this may be on my end, thinking about rebuilding from OS up. 
I tried again and I get this error, and a black screen on the CushyStuio window that pops up 


Starting Vite with Electron's Node...

Server running on http://localhost:8688
waiting for cushy to start
[VITE] vite started
[27512:0217/202012.547:ERROR:CONSOLE(0)] "ReferenceError: dragEvent is not defined", source:  (0)
[27512:0217/202052.892:ERROR:CONSOLE(0)] "ReferenceError: dragEvent is not defined", source:  (0)

![image](https://github.com/rvion/CushyStudio/assets/87996528/1e9ca61f-5560-49e1-a17d-134c5196db18)

I had in the past been able to reinstall and launch but this was on first launch. 



now I see in the devtools, :


main.js:23455 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
main.js:167182 [🛋️] rendering CushyStudio
main.js:151320 [🏷️] UserTags: 1 tags parsed
main.js:166837 [🛋️] starting Cushy
main.js:166685 [🍻] FIXUP TSConfig
main.js:154750 {0} Object
main.js:166850 [🛋️] 30 shortcuts loaded
main.js:159923 [🔑 AUTH] restoring session from DB...
main.js:159893 [🏷️] DanBooru: 100001 tags parsed
main.js:151756 [📑] comfy_schema: updating schema (virtual-base)
main.js:151756 [📑] comfy_schema: updating schema (virtual-full)
main.js:151756 [📑] comfy_schema: updating schema (standard)
main.js:167182 [🛋️] rendering CushyStudio
main.js:166837 [🛋️] starting Cushy
main.js:166685 [🍻] FIXUP TSConfig
main.js:154750 {1} Object
main.js:164538 Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.
_GoTrueClient @ main.js:164538
main.js:166850 [🛋️] 30 shortcuts loaded
main.js:159923 [🔑 AUTH] restoring session from DB...
main.js:151756 [📑] comfy_schema: updating schema (virtual-base)
main.js:151756 [📑] comfy_schema: updating schema (virtual-full)
main.js:151756 [📑] comfy_schema: updating schema (standard)
main.js:79070 Uncaught TypeError: nodeDef.output.entries is not a function or its return value is not iterable
    at ComfySchemaL.onUpdate (main.js:154527:52)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at ComfySchemaL.onUpdate (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at ComfySchemaL.init (main.js:151752:24)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at ComfySchemaL.init (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at LiveTable._createInstance (main.js:151629:16)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at LiveTable._createInstance (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at LiveTable.get (main.js:151429:19)
main.js:167182 [🛋️] rendering CushyStudio
main.js:166837 [🛋️] starting Cushy
main.js:166685 [🍻] FIXUP TSConfig
main.js:154750 {2} Object
main.js:164538 Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.
_GoTrueClient @ main.js:164538
main.js:166850 [🛋️] 30 shortcuts loaded
main.js:159923 [🔑 AUTH] restoring session from DB...
main.js:151756 [📑] comfy_schema: updating schema (virtual-base)
main.js:151756 [📑] comfy_schema: updating schema (virtual-full)
main.js:151756 [📑] comfy_schema: updating schema (standard)
main.js:167182 [🛋️] rendering CushyStudio
main.js:166837 [🛋️] starting Cushy
main.js:166685 [🍻] FIXUP TSConfig
main.js:154750 {3} Object
main.js:164538 Multiple GoTrueClient instances detected in the same browser context. It is not an error, but this should be avoided as it may produce undefined behavior when used concurrently under the same storage key.
_GoTrueClient @ main.js:164538
main.js:166850 [🛋️] 30 shortcuts loaded
main.js:159923 [🔑 AUTH] restoring session from DB...
main.js:151756 [📑] comfy_schema: updating schema (virtual-base)
main.js:151756 [📑] comfy_schema: updating schema (virtual-full)
main.js:151756 [📑] comfy_schema: updating schema (standard)
main.js:79070 Uncaught TypeError: nodeDef.output.entries is not a function or its return value is not iterable
    at ComfySchemaL.onUpdate (main.js:154527:52)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at ComfySchemaL.onUpdate (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at ComfySchemaL.init (main.js:151752:24)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at ComfySchemaL.init (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at LiveTable._createInstance (main.js:151629:16)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at LiveTable._createInstance (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at LiveTable.get (main.js:151429:19)
main.js:15955 The above error occurred in one of your React components:

    at http://localhost:8688/main.js:79108:12

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ main.js:15955
main.js:21328 Uncaught TypeError: nodeDef.output.entries is not a function or its return value is not iterable
    at ComfySchemaL.onUpdate (main.js:154527:52)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at ComfySchemaL.onUpdate (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at ComfySchemaL.init (main.js:151752:24)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at ComfySchemaL.init (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at LiveTable._createInstance (main.js:151629:16)
    at executeAction (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1241:15)
    at LiveTable._createInstance (C:\Users\user\Documents\CushyUI\CushyStudio\node_modules\mobx\dist\mobx.cjs.development.js:1226:12)
    at LiveTable.get (main.js:151429:19)
main.js:160041 [🔑 AUTH] 🟢 received INITIAL_SESSION
main.js:160041 [🔑 AUTH] 🟢 received INITIAL_SESSION
main.js:160041 [🔑 AUTH] 🟢 received INITIAL_SESSION
main.js:160041 [🔑 AUTH] 🟢 received INITIAL_SESSION
