### ISSUE TITLE
"Invalid method encountered' - Error connecting to ComfyUI Server

### ISSUE THREAD

**Issue by VOOM108** [rvion/CushyStudio#2]
When connecting to the running ComfyUI-Server in Cushy-Studio I get this error (in the terminal):

```
Traceback (most recent call last):
File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_[protocol.py](http://protocol.py/)", line 332, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

(Windows, Version from today)

**Comment by rvion** [comment]
I think it's probably related to comfy being in an earlier version 🤔 

could you tell me what steps you did, or what script did you run to get the crash ?

**Comment by VOOM108** [comment]
I updated ComfyUI to the latest version; now there is not even an error message in the terminal. It just does not connect to the server. 

I did not really do anything yet - installed Cushy Studio with the installer, started ComfyUI, started Cushy Studio, tried to connect to the server. Tried http://localhost:8188 as well as http://127.0.0.1:8188

**Comment by rvion** [comment]
oh; host is wrong, can you replace this with 127.0.0.1 ?
I'll change the field to make it allow both

**Comment by rvion** [comment]
Cushy currently expect  "host" to contains the IP 🤦. I need to fix this
I'll go with two separate inputs:
- http(s) url to access Comfy
- ws(s) url to access Comfy
so it accomodates various weird config with port forwarding, mixed ws/https protocol and other things

**Comment by VOOM108** [comment]
Without just the IP I get this: 

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

**Comment by VOOM108** [comment]
Nightly 0.0.39

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

There is no connect-button any more, should it connect automatically on startup now? 

As in the screenshot above, the error in CushyStudio relates to a CORS-issue. In A1111 for some extensions, I need to start the WebUI with a parameter allowing CORS. Could the connection be blocked because of that?

**Comment by rvion** [comment]
I'll improve the connection UI during my next code session 👍

**Comment by rvion** [comment]
@VOOM108 the connection flow is now vastly better; feel-free to re-open if you have any issue !
