### ISSUE TITLE
Error at start, it still works though 🤷‍♀️ 

### ISSUE THREAD

**Issue by noellealarie** [rvion/CushyStudio#34]
```
C:\CushyStudio>npm start

> cushystudio@0.0.99 start
> concurrently --kill-others -n vite,electron -c yellow,blue "npm run front:dev" "electron -i src/shell"

[electron]
[electron] [🍪] electronPath: C:\CushyStudio\node_modules\electron\dist
[electron] [🍪] icon path: C:\CushyStudio\src\public\CushyLogo-512.png
[electron] [🍪] failed to patch icon ExitCodeError: Command failed with a non-zero return code (1):
[electron] C:\CushyStudio\node_modules\rcedit\bin\rcedit-x64.exe C:\CushyStudio\node_modules\electron\dist\electron.exe --set-file-version CushyStudio --set-product-version CushyStudio --set-icon C:\CushyStudio\src\public\CushyLogo-512.png
[electron]
[electron] Fatal error: Unable to parse version string for FileVersion
[electron]     at ChildProcess.<anonymous> (C:\CushyStudio\node_modules\@malept\cross-spawn-promise\dist\src\index.js:99:24)
[electron]     at ChildProcess.emit (node:events:514:28)
[electron]     at cp.emit (C:\CushyStudio\node_modules\cross-spawn\lib\enoent.js:34:29)
[electron]     at maybeClose (node:internal/child_process:1091:16)
[electron]     at Socket.<anonymous> (node:internal/child_process:449:11)
[electron]     at Socket.emit (node:events:514:28)
[electron]     at Pipe.<anonymous> (node:net:323:12) {
[electron]   cmd: 'C:\\CushyStudio\\node_modules\\rcedit\\bin\\rcedit-x64.exe',
[electron]   args: [
[electron]     'C:\\CushyStudio\\node_modules\\electron\\dist\\electron.exe',
[electron]     '--set-file-version',
[electron]     'CushyStudio',
[electron]     '--set-product-version',
[electron]     'CushyStudio',
[electron]     '--set-icon',
[electron]     'C:\\CushyStudio\\src\\public\\CushyLogo-512.png'
[electron]   ],
[electron]   stdout: '',
[electron]   stderr: 'Fatal error: Unable to parse version string for FileVersion\r\n',
[electron]   code: 1
[electron] }
[electron] waiting for cushy to start
[vite]
[vite] > cushystudio@0.0.99 front:dev
[vite] > vite dev
[vite]
[vite]
[vite]   VITE v4.4.11  ready in 756 ms
[vite]
[vite]   ➜  Local:   http://localhost:8788/
[vite]   ➜  Network: use --host to expose
[electron] waiting for cushy to start
[electron] 200
```

**Comment by rvion** [comment]
found the fix; I'll try to push that this evening

**Comment by rvion** [comment]
I think this one is fixed :)
